[package]
edition = "2021"
name = "swc_plugins_utils"
version = "0.1.0"

[dependencies]
ahash = "0.8.2"
swc_core = {version = "0.51.1", features = [
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_transforms",
  "ecma_quote",
]}
