[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.71"
serde = "1.0.71"
serde_derive = "1.0.143"
swc = "0.223.0"
swc_ecma_parser = "0.118.3"
swc_common = "0.27.0"
swc_ecma_visit = "0.76.0"
swc_ecma_ast = "0.90.0"
swc_ecma_transforms = "0.190.0"
swc_ecma_transforms_base = "0.106.0"
swc_ecma_transforms_react = "0.148.0"
swc_ecma_transforms_typescript = "0.152.0"
swc_ecma_transforms_compat = "0.129.0"
swc_ecma_codegen = "0.123.0"
swc_ecma_utils = "0.101.0"
swc_ecma_minifier = "0.151.1"
swc_ecma_preset_env = "0.166.0"
swc_atoms = "0.4.8"
swc_ecma_transforms_testing = "0.108.0"
testing = "0.29.4"
anyhow = "1.0.62"
napi = { version = "2.0.0", features = ["napi7"] }
napi-derive = {version = "2.0.0", features = ["type-def"]}
